[build]
  # Comando de build principal
  command = "npm run build:netlify"
  
  # Directorio de publicaci贸n del frontend
  publish = "client/dist"
  
  # Directorio de las funciones serverless
  functions = "netlify/functions"
  
  # Variables de entorno para el build
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--include=dev"

# Configuraci贸n de headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Redirecciones para SPA y API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuraci贸n de formularios (si se necesita)
[functions]
  node_bundler = "nft"

# Configuraci贸n de Edge Functions (opcional)
# [[edge_functions]]
#   path = "/hello"
#   function = "hello"
